### ISSUE TITLE
make a CODEOWNERS

### ISSUE THREAD

**Issue by Ethan925** [bruthurs-inc/.github#1]
- [x] include everyone so we can tag all in PR reviews

![Image](https://github.com/bruthurs-inc/.github/assets/19763395/5b526ae8-cce4-4c3e-b78f-bad8b9588579)

**Comment by weefatboi** [comment]
As a note, CODEOWNERS has been iteratively added to every repo in our org (its required in each one). 

However, code ownership features won't work on any private repos (only public ones so, .github only in this case) unless we pay for GH Teams tier or higher. So the groundwork is there for it to work, but we need to pay for the feature to turn on
